spring.application.name=oauth2login
spring.security.user.name=user
spring.security.user.password=password

spring.devtools.restart.trigger-file=.reloadtrigger
spring.devtools.livereload.enabled=true

spring.security.oauth2.client.registration.google.client-id=1087999150954-t97t4koahep18s0nq9dog1mb87tte70v.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/contacts

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Google Cloud Service Account Credentials
spring.cloud.gcp.credentials.location=file:C:/Users/L14X18W04/Downloads/oauth2-web-926c35af9e3d.json